### ISSUE TITLE
Allow non-identifier characters, like - (hyphen), in messages

### ISSUE THREAD

**Issue by timalenus** [appsup-dart/intl_message#1]
When the string for a message contains a - (hyphen) the IntlMessage cannot be parsed and an exception is thrown.

For example I am trying to create a select message based on a Firebase id (which always starts with a hyphen):

`{reservation.group.id, select, -firebaseGroupId {pricemodel1} other {priceModel2}}`

**Comment by rbellens** [comment]
fixed in version 0.3.0
